// <auto-generated />
using FilmesApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmesApi.Migrations
{
    [DbContext(typeof(FilmesApiDbContext))]
    [Migration("20230702201735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmesApi.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diretor = "Jane Campion",
                            Duracao = 60,
                            Genero = "Suspense",
                            Nome = "Blade Runner"
                        },
                        new
                        {
                            Id = 2,
                            Diretor = "Jane Campion",
                            Duracao = 60,
                            Genero = "Suspense",
                            Nome = "Blade Runner2"
                        },
                        new
                        {
                            Id = 3,
                            Diretor = "Jane Campion",
                            Duracao = 60,
                            Genero = "Suspense",
                            Nome = "Blade Runner3"
                        },
                        new
                        {
                            Id = 4,
                            Diretor = "Jane Campion",
                            Duracao = 60,
                            Genero = "Suspense",
                            Nome = "Blade Runner4"
                        },
                        new
                        {
                            Id = 5,
                            Diretor = "Jane Campion",
                            Duracao = 60,
                            Genero = "Suspense",
                            Nome = "Blade Runner5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
